### ISSUE TITLE
关于文章中模型结果问题

### ISSUE THREAD

**Issue by fly-pandas** [thuiar/Self-MM#10]
你文章中报告的mae，corr 以及F1这三个结果，是采用第一种包括中立感情(即label=0)   还是采用第二种不包括中立感情时模型表现得效果吗？ 谢谢！

**Comment by Columbine21** [comment]
您好，mae和corr这两个回归指标都是所有样本的。分类指标acc-2和F1值在文章中都有提供 (neg./non-neg.) / (neg./pos.)
