### ISSUE TITLE
query ~~

### ISSUE THREAD

**Issue by jun0wanan** [thuiar/Self-MM#3]
hi,
      请教一下~ spatial differences  are difficult to represent the modality-specific difference ———中的 spatial differences 是什么呀？(●'◡'●)

best,
jun

**Comment by iyuge2** [comment]
在MISA这篇工作的“Difference Loss”部分，作者是用Frobenius范数距离约束模态一致性和模态特异性的表示，而这种范数距离在向量正交时取最小值，所以本质上还是向量点在空间上的距离或者角度约束关系。但是，在我们的理解上，模态特异性本身是一个非常抽象的概念，很难用空间上的距离或者角度进行度量。

**Comment by jun0wanan** [comment]
> 你好，在MISA这篇工作的“Difference Loss”部分，作者是用Frobenius范数距离约束模态一致性和模态特异性的表示，而这种范数距离在向量正交时取最小值，所以本质上还是向量点在空间上的距离或者角度约束关系。但是，在我们的理解上，模态特异性本身是一个非常抽象的概念，很难用空间上的距离或者角度进行度量。

感谢您的回复

**Comment by jun0wanan** [comment]
> 你好，在MISA这篇工作的“Difference Loss”部分，作者是用Frobenius范数距离约束模态一致性和模态特异性的表示，而这种范数距离在向量正交时取最小值，所以本质上还是向量点在空间上的距离或者角度约束关系。但是，在我们的理解上，模态特异性本身是一个非常抽象的概念，很难用空间上的距离或者角度进行度量。

再请教一下，MSA的标签的 regression标签 是本身自带的吗~

**Comment by iyuge2** [comment]
嗯嗯，多模态的标签是数据集自带的
