### ISSUE TITLE
About the result on MOSI

### ISSUE THREAD

**Issue by lzjjeff** [thuiar/Self-MM#4]
你好~我按照README上的步骤试着在自己的电脑上跑了一下代码，在mosi上的结果和论文里的有些差距：

Has0_acc_2=82.97
Has0_F1_score=82.99
Non0_acc_2=84.6
Non0_F1_score=84.57
MAE=72.52
Corr=79.44

因为论文中提到的结果是5次结果的平均，这样的差距让人有点意外。

除了transformers==4.4.2以外，requirements.txt内所要求的环境都满足，另外我的cuda版本为10.2。

请问我需要更改模型参数或者训练参数吗？能否提供更为详细的环境信息呢？

期待回复~

**Comment by iyuge2** [comment]
Please see [Issue 2](https://github.com/thuiar/Self-MM/issues/2). Thanks~

**Comment by lzjjeff** [comment]
> Please see [Issue 2](https://github.com/thuiar/Self-MM/issues/2). Thanks~

好的，感谢~

**Comment by leijue222** [comment]
@lzjjeff Have you achieved results comparable to those of the paper?
My result is similar to yours, but this result is still a bit worse than the paper result.

**Comment by lzjjeff** [comment]
> @lzjjeff Have you achieved results comparable to those of the paper?
> My result is similar to yours, but this result is still a bit worse than the paper result.

Not yet. I re-run it with the new config file updated in May but got similar results to my previous one.

**Comment by leijue222** [comment]
> Unfortunately, we lost the original parameters in our paper when we re-run all models and datasets. But you can try the following parameters, which can get comparable or better results than our work in AAAI 2021.

Too sad... I tried a lot but couldn't get results comparable to the paper...
