### ISSUE TITLE
Questions about MIN values

### ISSUE THREAD

**Issue by Nihility-Protoss** [thuiar/Self-MM#5]
感谢你的贡献！颇有学习意义。

在研读您的论文和代码时，SELF_MM.py中的updata_labels函数与论文中的描述有些不同，代码在多个地方使用MIN值，而非论文的仅一个地方，是有何考虑吗？如第281行中的MIN值。
源代码：
https://github.com/thuiar/Self-MM/blob/c4525c15f9c16859a371d48e0c822172eb4b2312/trains/multiTask/SELF_MM.py#L276-L281
论文中：
![image](https://user-images.githubusercontent.com/72033792/118510475-92f35d00-b763-11eb-923d-c054d17df47c.png)

**Comment by iyuge2** [comment]
你好，感谢你的关注。这个MIN值是一个非常小的正数，用于避免除零异常。281行对应论文中公式8的\alpha_s / \alphs_m，此处的确应该类似公式5加上\sigma常数。谢谢！

**Comment by KaetheFu** [comment]
您好，在运行代码时遇到向量唯独维度不匹配的问题，请问这个是我的配置问题吗？
RuntimeError: size mismatch, m1: [16 x 21176], m2: [816 x 128] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:273

**Comment by iyuge2** [comment]
是不是超参数配置错了，或者数据加载出错？按理说应该是不会出现这个问题的。
